### ISSUE TITLE
Island can't be generated!

### ISSUE THREAD

**Issue by ghost** [GiantAmethyst/SkyBlock#17]
When I run the command /skyblock create  I get a bunch of errors in my server log.
You can find my server's log output at this link...
`https://gist.github.com/angusbeefsteak/d58c77f9787ba6a155944c528cea4deb`

I researched this, and I think that your plugin is trying to use the method setBiomeColor() but this was taken out in MCPE 1.0.0

If it Helps...
Server OS: Unkown (Hosting Company)
Server Software: BlueLight PocketMine 1.0.0
Client Version: 1.0.0

**Comment by iawsomecreeper** [comment]
Same problem
when i tp to the island it wont load. 


Server Software Elywing 1.0

**Comment by bulutsun** [comment]
https://github.com/bulutsun/SkyBlock/tree/patch-2 fixed.
