### ISSUE TITLE
setBiomeColor Bug

### ISSUE THREAD

**Issue by XFizzer** [GiantAmethyst/SkyBlock#18]
20.02 13:06:05 [Server] Asynchronous Worker #1 thread/CRITICAL Error: "Call to undefined method pocketmine\level\format\Chunk::setBiomeColor()" (EXCEPTION) in "/SkyBlock-0.1.7.phar/src/SkyBlock/generator/generators/BasicIsland" at line 107

**Comment by bulutsun** [comment]
https://github.com/bulutsun/SkyBlock/tree/patch-2 fixed.

**Comment by huybinh2009** [comment]
Unhandled exception executing command 'sb create' in skyblock: Call to undefined method pocketmine\level\Level::getlevel()
2017-04-05 [20:53:05] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\level\Level::getlevel()" (EXCEPTION) in "/plugins/SkyBlock/src/SkyBlock/skyblock/SkyBlockManager" at line 48
 how to fix
